//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralMaterial()
        {
            this.GeneralTaskMaterials = new HashSet<GeneralTaskMaterial>();
        }
    
        public int MaterialID { get; set; }
        public int VendorID { get; set; }
        public string MaterialProduct { get; set; }
        public Nullable<int> ColorLookupID { get; set; }
        public int MaterialTypeLookupID { get; set; }
        public int Quantity { get; set; }
        public int UomLookupID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Lookup MaterialType { get; set; }
        public virtual Lookup UOM { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralTaskMaterial> GeneralTaskMaterials { get; set; }
        public virtual Lookup Color { get; set; }
    }
}
