//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTaskMaterial
    {
        public int GenTaskMaterialID { get; set; }
        public int GenTaskID { get; set; }
        public int GenMaterialID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual GeneralMaterial GeneralMaterial { get; set; }
        public virtual GeneralTask GeneralTask { get; set; }
    }
}
