//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralPlan()
        {
            this.GeneralPlanTasks = new HashSet<GeneralPlanTask>();
        }
    
        public int GenPlanID { get; set; }
        public string PlanName { get; set; }
        public int ElevationLookupID { get; set; }
        public int GarageTypeLookupID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralPlanTask> GeneralPlanTasks { get; set; }
        public virtual Lookup Elevation { get; set; }
        public virtual Lookup GarageType { get; set; }
    }
}
