//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public int LookupID { get; set; }
        public int LookupTypeID { get; set; }
        public string LookupValue { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int LastUpdatedBy { get; set; }
    }
}
