//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int MaterialID { get; set; }
        public int VendorID { get; set; }
        public string MaterialProduct { get; set; }
        public string Color { get; set; }
        public int CategoryID { get; set; }
        public int Quantity { get; set; }
        public int UomID { get; set; }
    }
}
