USE [master]
GO

/****** Object:  Database [ConstructionManager]    Script Date: 8/3/2017 6:31:06 PM ******/
CREATE DATABASE [ConstructionManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ConstructionManager', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\ConstructionManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ConstructionManager_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\ConstructionManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ConstructionManager] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ConstructionManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ConstructionManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ConstructionManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ConstructionManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ConstructionManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ConstructionManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [ConstructionManager] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ConstructionManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ConstructionManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ConstructionManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ConstructionManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ConstructionManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ConstructionManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ConstructionManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ConstructionManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ConstructionManager] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ConstructionManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ConstructionManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ConstructionManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ConstructionManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ConstructionManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ConstructionManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ConstructionManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ConstructionManager] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ConstructionManager] SET  MULTI_USER 
GO

ALTER DATABASE [ConstructionManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ConstructionManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ConstructionManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ConstructionManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ConstructionManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ConstructionManager] SET QUERY_STORE = OFF
GO

USE [ConstructionManager]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ConstructionManager] SET  READ_WRITE 
GO

